name: Download Quartobook

on:
  workflow_dispatch:

jobs:
  download:
    runs-on: ubuntu-latest
    permissions:
      actions: read
      contents: read

    steps:
      - name: Download quartobook artifact
        uses: dawidd6/action-download-artifact@v2
        with:
          repo: edalfon/ptfr
          github_token: ${{ secrets.GITHUB_TOKEN }}
          workflow: R-targets.yml
          workflow_conclusion: success
          branch: main
          path: book
          search_artifacts: true
          check_artifacts: true
